//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrapperWebForms.Pages {
    public partial class Upload : System.Web.UI.Page {
    }
}
